create table Groups (
	ID INT,
	Description VARCHAR(50),
	Admin VARCHAR(50),
	Name TEXT
);
insert into Groups (ID, Description, Admin, Name) values (1, 'Nondisplaced spiral fracture of shaft of ulna, left arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing', 0, 'molestie');
insert into Groups (ID, Description, Admin, Name) values (2, 'Unspecified injury of flexor muscle, fascia and tendon of left ring finger at forearm level, subsequent encounter', 0, 'nisi');
insert into Groups (ID, Description, Admin, Name) values (3, 'Displaced apophyseal fracture of left femur, subsequent encounter for open fracture type I or II with nonunion', 1, 'nunc rhoncus');
insert into Groups (ID, Description, Admin, Name) values (4, 'Fracture of angle of right mandible, subsequent encounter for fracture with routine healing', 0, 'porttitor lorem');
insert into Groups (ID, Description, Admin, Name) values (5, 'Struck by baseball bat, initial encounter', 1, 'id luctus nec');
insert into Groups (ID, Description, Admin, Name) values (6, 'Legal intervention involving other specified means, bystander injured, sequela', 0, 'erat');
insert into Groups (ID, Description, Admin, Name) values (7, 'Unspecified fracture of shaft of left fibula, subsequent encounter for closed fracture with malunion', 0, 'maecenas tristique');
insert into Groups (ID, Description, Admin, Name) values (8, 'Other fracture of shaft of radius, unspecified arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 0, 'fusce consequat nulla');
insert into Groups (ID, Description, Admin, Name) values (9, 'Dislocation of midcarpal joint of unspecified wrist', 1, 'quisque porta volutpat');
insert into Groups (ID, Description, Admin, Name) values (10, 'Other specified injury of unspecified blood vessel at lower leg level, right leg', 1, 'semper rutrum nulla');
insert into Groups (ID, Description, Admin, Name) values (11, 'Hypertrichosis of unspecified eye, unspecified eyelid', 1, 'vel');
insert into Groups (ID, Description, Admin, Name) values (12, 'Sprain of interphalangeal joint of left middle finger, sequela', 0, 'ipsum');
insert into Groups (ID, Description, Admin, Name) values (13, 'Obesity, unspecified', 0, 'molestie nibh');
insert into Groups (ID, Description, Admin, Name) values (14, 'Laceration of peroneal artery, right leg, subsequent encounter', 1, 'in est');
insert into Groups (ID, Description, Admin, Name) values (15, 'Left sided colitis with unspecified complications', 0, 'hac habitasse');
insert into Groups (ID, Description, Admin, Name) values (16, 'Aggressive periodontitis, generalized, severe', 1, 'at feugiat non');
insert into Groups (ID, Description, Admin, Name) values (17, 'Blister (nonthermal) of right upper arm, initial encounter', 1, 'diam neque vestibulum');
insert into Groups (ID, Description, Admin, Name) values (18, 'Unspecified traumatic displaced spondylolisthesis of second cervical vertebra, initial encounter for closed fracture', 1, 'diam');
insert into Groups (ID, Description, Admin, Name) values (19, 'Superficial foreign body, unspecified foot, initial encounter', 1, 'magna');
insert into Groups (ID, Description, Admin, Name) values (20, 'Puncture wound without foreign body of left thumb with damage to nail, sequela', 0, 'vivamus in');
insert into Groups (ID, Description, Admin, Name) values (21, 'War operations involving unintentional restriction of air and airway, military personnel', 0, 'tortor eu pede');
insert into Groups (ID, Description, Admin, Name) values (22, 'Occupant of animal-drawn vehicle injured in collision with other nonmotor vehicles, sequela', 0, 'ipsum primis in');
insert into Groups (ID, Description, Admin, Name) values (23, 'Superficial frostbite of knee and lower leg', 0, 'eleifend luctus ultricies');
insert into Groups (ID, Description, Admin, Name) values (24, 'Lead-induced chronic gout, unspecified knee', 1, 'rutrum');
insert into Groups (ID, Description, Admin, Name) values (25, 'Poisoning by other topical agents, accidental (unintentional)', 0, 'sapien');
insert into Groups (ID, Description, Admin, Name) values (26, 'Displaced comminuted fracture of shaft of radius, unspecified arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 0, 'elementum nullam varius');
insert into Groups (ID, Description, Admin, Name) values (27, 'Other migraine, intractable, without status migrainosus', 0, 'felis');
insert into Groups (ID, Description, Admin, Name) values (28, 'Temporary auditory threshold shift, bilateral', 0, 'varius');
insert into Groups (ID, Description, Admin, Name) values (29, 'Person boarding or alighting a heavy transport vehicle injured in collision with other nonmotor vehicle', 1, 'pellentesque');
insert into Groups (ID, Description, Admin, Name) values (30, 'Hodgkin lymphoma, unspecified, intrapelvic lymph nodes', 1, 'eu tincidunt');
insert into Groups (ID, Description, Admin, Name) values (31, 'Nondisplaced dome fracture of unspecified acetabulum', 0, 'commodo');
insert into Groups (ID, Description, Admin, Name) values (32, 'Burn of second degree of unspecified single finger (nail) except thumb, initial encounter', 1, 'sed');
insert into Groups (ID, Description, Admin, Name) values (33, 'Major depressive disorder, recurrent, severe with psychotic symptoms', 0, 'ut mauris eget');
insert into Groups (ID, Description, Admin, Name) values (34, 'Gestational [pregnancy-induced] hypertension without significant proteinuria, second trimester', 1, 'facilisi cras non');
insert into Groups (ID, Description, Admin, Name) values (35, 'Other balloon accident injuring occupant, subsequent encounter', 1, 'integer tincidunt');
insert into Groups (ID, Description, Admin, Name) values (36, 'Fall from other flat-bottomed pedestrian conveyance, initial encounter', 1, 'ridiculus');
insert into Groups (ID, Description, Admin, Name) values (37, 'Nondisplaced segmental fracture of shaft of left fibula, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 0, 'iaculis congue vivamus');
insert into Groups (ID, Description, Admin, Name) values (38, 'Explosion on board passenger ship, initial encounter', 1, 'ipsum dolor');
insert into Groups (ID, Description, Admin, Name) values (39, 'Corrosion of second degree of multiple sites of left wrist and hand, initial encounter', 0, 'maecenas rhoncus aliquam');
insert into Groups (ID, Description, Admin, Name) values (40, 'Fracture of third cervical vertebra', 1, 'volutpat in congue');
insert into Groups (ID, Description, Admin, Name) values (41, 'Epidermolysis bullosa letalis', 0, 'potenti cras in');
insert into Groups (ID, Description, Admin, Name) values (42, 'Nondisplaced supracondylar fracture with intracondylar extension of lower end of right femur, subsequent encounter for closed fracture with malunion', 0, 'blandit');
insert into Groups (ID, Description, Admin, Name) values (43, 'Other injury of other muscle(s) and tendon(s) at lower leg level, unspecified leg, subsequent encounter', 1, 'elementum pellentesque quisque');
insert into Groups (ID, Description, Admin, Name) values (44, 'Transitory neonatal hypoparathyroidism', 1, 'nisl nunc nisl');
insert into Groups (ID, Description, Admin, Name) values (45, 'Failure in dosage during other surgical and medical care', 1, 'massa id');
insert into Groups (ID, Description, Admin, Name) values (46, 'Unspecified occupant of pick-up truck or van injured in collision with railway train or railway vehicle in traffic accident, initial encounter', 1, 'rhoncus sed');
insert into Groups (ID, Description, Admin, Name) values (47, 'Partial traumatic amputation of unspecified midfoot, initial encounter', 1, 'ut massa quis');
insert into Groups (ID, Description, Admin, Name) values (48, 'Extravasation of urine', 0, 'interdum venenatis');
insert into Groups (ID, Description, Admin, Name) values (49, 'Autoimmune hepatitis', 1, 'ac');
insert into Groups (ID, Description, Admin, Name) values (50, 'Puncture wound with foreign body of unspecified external genital organs, female, sequela', 1, 'tincidunt');
insert into Groups (ID, Description, Admin, Name) values (51, 'Displaced transverse fracture of right patella, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', 1, 'tristique fusce');
insert into Groups (ID, Description, Admin, Name) values (52, 'Displaced fracture of distal phalanx of left thumb, subsequent encounter for fracture with nonunion', 0, 'sapien ut');
insert into Groups (ID, Description, Admin, Name) values (53, 'Displaced segmental fracture of shaft of radius, unspecified arm, subsequent encounter for closed fracture with delayed healing', 0, 'orci vehicula condimentum');
insert into Groups (ID, Description, Admin, Name) values (54, 'Adverse effect of cannabis (derivatives), subsequent encounter', 1, 'ac leo pellentesque');
insert into Groups (ID, Description, Admin, Name) values (55, 'Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder with hallucinations', 0, 'donec dapibus');
insert into Groups (ID, Description, Admin, Name) values (56, 'Displaced articular fracture of head of unspecified femur, initial encounter for open fracture type I or II', 0, 'dui vel');
insert into Groups (ID, Description, Admin, Name) values (57, 'Other contact with goose, initial encounter', 1, 'ante');
insert into Groups (ID, Description, Admin, Name) values (58, 'Toxic effect of rattlesnake venom, undetermined, sequela', 1, 'libero ut');
insert into Groups (ID, Description, Admin, Name) values (59, 'Fracture of lateral condyle of humerus', 0, 'pharetra magna ac');
insert into Groups (ID, Description, Admin, Name) values (60, 'Other herpesviral infection', 1, 'semper interdum mauris');
insert into Groups (ID, Description, Admin, Name) values (61, 'Fracture of alveolus of mandible, unspecified side, subsequent encounter for fracture with routine healing', 1, 'metus sapien');
insert into Groups (ID, Description, Admin, Name) values (62, 'Nondisplaced trimalleolar fracture of unspecified lower leg, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing', 0, 'ipsum primis in');
insert into Groups (ID, Description, Admin, Name) values (63, 'Other fracture of lower end of right femur, subsequent encounter for closed fracture with delayed healing', 0, 'augue');
insert into Groups (ID, Description, Admin, Name) values (64, 'Other conjunctivitis', 1, 'mi in');
insert into Groups (ID, Description, Admin, Name) values (65, 'Medial subluxation of left ulnohumeral joint', 1, 'amet erat');
insert into Groups (ID, Description, Admin, Name) values (66, 'Displaced fracture of medial malleolus of unspecified tibia, sequela', 0, 'non pretium');
insert into Groups (ID, Description, Admin, Name) values (67, 'Contusion of small intestine', 1, 'pede');
insert into Groups (ID, Description, Admin, Name) values (68, 'Other conjunctivitis', 0, 'consequat');
insert into Groups (ID, Description, Admin, Name) values (69, 'Acute bronchitis due to coxsackievirus', 1, 'ut nunc');
insert into Groups (ID, Description, Admin, Name) values (70, 'Subluxation of other carpometacarpal joint of left hand, subsequent encounter', 1, 'duis faucibus');
insert into Groups (ID, Description, Admin, Name) values (71, 'Salter-Harris Type III physeal fracture of lower end of humerus, left arm, subsequent encounter for fracture with delayed healing', 0, 'sapien a');
insert into Groups (ID, Description, Admin, Name) values (72, 'Other fracture of base of skull, initial encounter for open fracture', 1, 'nulla sed');
insert into Groups (ID, Description, Admin, Name) values (73, 'External constriction of left upper arm, initial encounter', 1, 'aliquet');
insert into Groups (ID, Description, Admin, Name) values (74, 'Breakdown (mechanical) of vascular dialysis catheter, initial encounter', 1, 'integer tincidunt ante');
insert into Groups (ID, Description, Admin, Name) values (75, 'Displaced intraarticular fracture of right calcaneus, subsequent encounter for fracture with routine healing', 1, 'rhoncus');
insert into Groups (ID, Description, Admin, Name) values (76, 'Torus fracture of lower end of right ulna, initial encounter for closed fracture', 1, 'eu');
insert into Groups (ID, Description, Admin, Name) values (77, 'Complete traumatic transphalangeal amputation of thumb', 0, 'vivamus tortor duis');
insert into Groups (ID, Description, Admin, Name) values (78, 'Abnormal oculomotor study', 0, 'justo nec condimentum');
insert into Groups (ID, Description, Admin, Name) values (79, 'Fall on same level from slipping, tripping and stumbling with subsequent striking against furniture, sequela', 1, 'primis in');
insert into Groups (ID, Description, Admin, Name) values (80, 'Neoplasm of uncertain behavior of unspecified adrenal gland', 1, 'vel');
insert into Groups (ID, Description, Admin, Name) values (81, 'Puncture wound with foreign body of other specified part of neck', 0, 'nam');
insert into Groups (ID, Description, Admin, Name) values (82, 'Adverse effect of mixed bacterial vaccines without a pertussis component, sequela', 0, 'tristique');
insert into Groups (ID, Description, Admin, Name) values (83, 'Laceration without foreign body of right buttock', 1, 'morbi ut odio');
insert into Groups (ID, Description, Admin, Name) values (84, 'Post-traumatic stress disorder, unspecified', 0, 'erat vestibulum');
insert into Groups (ID, Description, Admin, Name) values (85, 'Open wound of toe without damage to nail', 1, 'sapien non');
insert into Groups (ID, Description, Admin, Name) values (86, 'Chondromalacia, joints of right hand', 0, 'pretium quis');
insert into Groups (ID, Description, Admin, Name) values (87, 'Displaced fracture of distal phalanx of right ring finger', 1, 'est');
insert into Groups (ID, Description, Admin, Name) values (88, 'Postprocedural adrenocortical (-medullary) hypofunction', 1, 'posuere');
insert into Groups (ID, Description, Admin, Name) values (89, 'Crohn''s disease, unspecified, with other complication', 1, 'a pede posuere');
insert into Groups (ID, Description, Admin, Name) values (90, 'Contusion of right hip', 0, 'dictumst morbi vestibulum');
insert into Groups (ID, Description, Admin, Name) values (91, 'External constriction of right elbow, sequela', 0, 'blandit nam nulla');
insert into Groups (ID, Description, Admin, Name) values (92, 'Burn of first degree of unspecified shoulder, subsequent encounter', 0, 'volutpat erat quisque');
insert into Groups (ID, Description, Admin, Name) values (93, 'Unspecified superficial injury of left knee', 1, 'eget tincidunt eget');
insert into Groups (ID, Description, Admin, Name) values (94, 'Nondisplaced comminuted fracture of shaft of humerus, left arm, initial encounter for open fracture', 1, 'eget eros');
insert into Groups (ID, Description, Admin, Name) values (95, 'Displaced fracture of body of unspecified calcaneus, subsequent encounter for fracture with nonunion', 1, 'porta volutpat');
insert into Groups (ID, Description, Admin, Name) values (96, 'Maternal care for disproportion of mixed maternal and fetal origin, not applicable or unspecified', 1, 'in hac habitasse');
insert into Groups (ID, Description, Admin, Name) values (97, 'Toxic effect of rattlesnake venom, intentional self-harm', 1, 'non sodales sed');
insert into Groups (ID, Description, Admin, Name) values (98, 'Poisoning by cocaine, intentional self-harm, initial encounter', 1, 'dis parturient montes');
insert into Groups (ID, Description, Admin, Name) values (99, 'Displaced spiral fracture of shaft of unspecified fibula, subsequent encounter for closed fracture with malunion', 1, 'suspendisse potenti');
insert into Groups (ID, Description, Admin, Name) values (100, 'Laceration with foreign body of left back wall of thorax with penetration into thoracic cavity', 1, 'vel dapibus');
insert into Groups (ID, Description, Admin, Name) values (101, 'Salpingitis and oophoritis, unspecified', 1, 'ut odio');
insert into Groups (ID, Description, Admin, Name) values (102, 'Pathological fracture in other disease, right ulna, subsequent encounter for fracture with malunion', 1, 'in hac habitasse');
insert into Groups (ID, Description, Admin, Name) values (103, 'Military operations involving unspecified weapon of mass destruction [WMD], initial encounter', 1, 'ut dolor');
insert into Groups (ID, Description, Admin, Name) values (104, 'Nondisplaced fracture of medial condyle of right tibia, subsequent encounter for open fracture type I or II with delayed healing', 0, 'in eleifend quam');
insert into Groups (ID, Description, Admin, Name) values (105, 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema', 0, 'lectus');
insert into Groups (ID, Description, Admin, Name) values (106, 'Other chondrocalcinosis, left shoulder', 0, 'amet eleifend');
insert into Groups (ID, Description, Admin, Name) values (107, 'Other tear of unspecified meniscus, current injury, right knee, subsequent encounter', 0, 'aliquam');
insert into Groups (ID, Description, Admin, Name) values (108, 'Unspecified fracture of shaft of left tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 0, 'purus sit');
insert into Groups (ID, Description, Admin, Name) values (109, 'Posterior subluxation of unspecified sternoclavicular joint, initial encounter', 0, 'nulla suscipit');
insert into Groups (ID, Description, Admin, Name) values (110, 'Other superficial bite of unspecified thumb, sequela', 0, 'dapibus at diam');
insert into Groups (ID, Description, Admin, Name) values (111, 'Cellulitis and acute lymphangitis of other sites', 0, 'porta');
insert into Groups (ID, Description, Admin, Name) values (112, 'Posterior displaced fracture of sternal end of left clavicle, subsequent encounter for fracture with delayed healing', 0, 'libero ut massa');
insert into Groups (ID, Description, Admin, Name) values (113, 'Typhoid pneumonia', 0, 'cum sociis natoque');
insert into Groups (ID, Description, Admin, Name) values (114, 'Noninfective disorders of pinna, right ear', 1, 'sit amet turpis');
insert into Groups (ID, Description, Admin, Name) values (115, 'Corrosion of first degree of right hand, unspecified site, initial encounter', 0, 'porttitor id consequat');
insert into Groups (ID, Description, Admin, Name) values (116, 'Hypertrophy of nasal turbinates', 0, 'blandit lacinia');
insert into Groups (ID, Description, Admin, Name) values (117, 'Venous insufficiency (chronic) (peripheral)', 0, 'ipsum');
insert into Groups (ID, Description, Admin, Name) values (118, 'Displaced fracture of greater trochanter of right femur, initial encounter for closed fracture', 1, 'metus');
insert into Groups (ID, Description, Admin, Name) values (119, 'Passenger in three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus in traffic accident, subsequent encounter', 0, 'velit');
insert into Groups (ID, Description, Admin, Name) values (120, 'Nondisplaced fracture of lateral condyle of right femur, initial encounter for closed fracture', 1, 'augue');
insert into Groups (ID, Description, Admin, Name) values (121, 'Eosinophilic esophagitis', 0, 'justo');
insert into Groups (ID, Description, Admin, Name) values (122, 'Unspecified physeal fracture of right  metatarsal, subsequent encounter for fracture with delayed healing', 1, 'nullam');
insert into Groups (ID, Description, Admin, Name) values (123, 'Osteonecrosis in diseases classified elsewhere, hand', 0, 'pulvinar sed');
insert into Groups (ID, Description, Admin, Name) values (124, 'Retinopathy of prematurity, stage 5', 1, 'erat eros viverra');
insert into Groups (ID, Description, Admin, Name) values (125, 'Nondisplaced fracture of anterior process of left calcaneus, sequela', 1, 'suscipit');
insert into Groups (ID, Description, Admin, Name) values (126, 'Enteropathic arthropathies, right wrist', 1, 'ut massa volutpat');
insert into Groups (ID, Description, Admin, Name) values (127, 'Nondisplaced transcondylar fracture of left humerus', 0, 'accumsan');
insert into Groups (ID, Description, Admin, Name) values (128, 'Burn involving larynx and trachea with lung, initial encounter', 0, 'morbi ut');
insert into Groups (ID, Description, Admin, Name) values (129, 'Acute inflammation of orbit', 1, 'nulla ut');
insert into Groups (ID, Description, Admin, Name) values (130, 'Corrosion of third degree back of unspecified hand', 0, 'ipsum dolor');
insert into Groups (ID, Description, Admin, Name) values (131, 'Calcium deposit in bursa, multiple sites', 0, 'quisque');
insert into Groups (ID, Description, Admin, Name) values (132, 'Exudative age-related macular degeneration, right eye', 1, 'congue');
insert into Groups (ID, Description, Admin, Name) values (133, 'Food in trachea causing other injury, subsequent encounter', 1, 'erat eros viverra');
insert into Groups (ID, Description, Admin, Name) values (134, 'Age-related osteoporosis with current pathological fracture, right humerus, initial encounter for fracture', 0, 'nunc viverra dapibus');
insert into Groups (ID, Description, Admin, Name) values (135, 'Degeneration of iris (pigmentary), right eye', 1, 'nonummy integer non');
insert into Groups (ID, Description, Admin, Name) values (136, 'Failed moderate sedation during procedure, subsequent encounter', 0, 'suspendisse');
insert into Groups (ID, Description, Admin, Name) values (137, 'Other fracture of shaft of right ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 1, 'tellus semper');
insert into Groups (ID, Description, Admin, Name) values (138, 'Burn of third degree of unspecified elbow, subsequent encounter', 0, 'vitae mattis');
insert into Groups (ID, Description, Admin, Name) values (139, 'Retained (old) magnetic foreign body in anterior chamber, bilateral', 1, 'integer ac');
insert into Groups (ID, Description, Admin, Name) values (140, 'Osteochondritis dissecans, right hip', 1, 'dictumst morbi vestibulum');
insert into Groups (ID, Description, Admin, Name) values (141, 'War operations involving gasoline bomb, civilian, initial encounter', 1, 'sem');
insert into Groups (ID, Description, Admin, Name) values (142, 'Maternal care for disproportion, unspecified', 0, 'cras pellentesque');
insert into Groups (ID, Description, Admin, Name) values (143, 'Burn of third degree of back of left hand, initial encounter', 0, 'odio in hac');
insert into Groups (ID, Description, Admin, Name) values (144, 'Unspecified fracture of head of right femur, initial encounter for open fracture type I or II', 1, 'morbi odio');
insert into Groups (ID, Description, Admin, Name) values (145, 'Terrorism involving destruction of aircraft, terrorist injured, initial encounter', 1, 'massa quis');
insert into Groups (ID, Description, Admin, Name) values (146, 'Personal history of malignant neoplasm of other female genital organs', 1, 'in faucibus orci');
insert into Groups (ID, Description, Admin, Name) values (147, 'Nondisplaced fracture of medial condyle of right femur', 1, 'nibh');
insert into Groups (ID, Description, Admin, Name) values (148, 'Primary optic atrophy, unspecified eye', 1, 'consequat dui');
insert into Groups (ID, Description, Admin, Name) values (149, 'Nondisplaced fracture of medial condyle of left tibia, subsequent encounter for open fracture type I or II with delayed healing', 1, 'vestibulum eget');
insert into Groups (ID, Description, Admin, Name) values (150, 'Displaced fracture of epiphysis (separation) (upper) of left femur, subsequent encounter for open fracture type I or II with delayed healing', 0, 'ante ipsum primis');
insert into Groups (ID, Description, Admin, Name) values (151, 'Unspecified fracture of shaft of unspecified femur, subsequent encounter for open fracture type I or II with delayed healing', 0, 'magnis dis');
insert into Groups (ID, Description, Admin, Name) values (152, 'Poisoning by dental drugs, topically applied, undetermined, sequela', 1, 'nulla');
insert into Groups (ID, Description, Admin, Name) values (153, 'Subluxation of unspecified interphalangeal joint of left thumb, sequela', 0, 'eu sapien cursus');
insert into Groups (ID, Description, Admin, Name) values (154, 'Other specified injury of popliteal vein, left leg, initial encounter', 1, 'tortor sollicitudin');
insert into Groups (ID, Description, Admin, Name) values (155, 'Other conditions associated with Lyme disease', 0, 'montes');
insert into Groups (ID, Description, Admin, Name) values (156, 'Laceration without foreign body of right back wall of thorax with penetration into thoracic cavity, subsequent encounter', 0, 'eleifend pede');
insert into Groups (ID, Description, Admin, Name) values (157, 'Injury of unspecified nerve at ankle and foot level, left leg', 1, 'mauris');
insert into Groups (ID, Description, Admin, Name) values (158, 'Flexural eczema', 1, 'turpis elementum');
insert into Groups (ID, Description, Admin, Name) values (159, 'Unspecified behavioral and emotional disorders with onset usually occurring in childhood and adolescence', 1, 'odio in');
insert into Groups (ID, Description, Admin, Name) values (160, 'Carcinoma in situ of bronchus and lung', 1, 'risus');
insert into Groups (ID, Description, Admin, Name) values (161, 'Flail joint, unspecified shoulder', 1, 'commodo placerat praesent');
insert into Groups (ID, Description, Admin, Name) values (162, 'Displaced unspecified condyle fracture of lower end of right femur, subsequent encounter for open fracture type I or II with malunion', 0, 'molestie sed');
insert into Groups (ID, Description, Admin, Name) values (163, 'Major laceration of left internal jugular vein, sequela', 1, 'adipiscing elit');
insert into Groups (ID, Description, Admin, Name) values (164, 'Trench fever', 1, 'posuere cubilia curae');
insert into Groups (ID, Description, Admin, Name) values (165, 'War operations involving firearms pellets, military personnel', 0, 'odio curabitur');
insert into Groups (ID, Description, Admin, Name) values (166, 'Sudden visual loss, left eye', 0, 'mattis');
insert into Groups (ID, Description, Admin, Name) values (167, 'Major laceration of greater saphenous vein at hip and thigh level, right leg', 1, 'nec molestie');
insert into Groups (ID, Description, Admin, Name) values (168, 'Anterior subcapsular polar infantile and juvenile cataract, right eye', 0, 'nunc');
insert into Groups (ID, Description, Admin, Name) values (169, 'Nondisplaced comminuted fracture of shaft of right fibula, subsequent encounter for closed fracture with malunion', 1, 'amet sapien');
insert into Groups (ID, Description, Admin, Name) values (170, 'Traumatic rupture of unspecified ligament of right ring finger at metacarpophalangeal and interphalangeal joint', 0, 'eu');
insert into Groups (ID, Description, Admin, Name) values (171, 'Type III traumatic spondylolisthesis of second cervical vertebra, initial encounter for closed fracture', 0, 'ut nunc vestibulum');
insert into Groups (ID, Description, Admin, Name) values (172, 'Problems in relationship with spouse or partner', 1, 'imperdiet et');
insert into Groups (ID, Description, Admin, Name) values (173, 'Burn of third degree of right scapular region', 0, 'eu nibh quisque');
insert into Groups (ID, Description, Admin, Name) values (174, 'Histoplasmosis capsulati, unspecified', 0, 'porttitor');
insert into Groups (ID, Description, Admin, Name) values (175, 'Contusion of unspecified ankle, initial encounter', 0, 'dictumst');
insert into Groups (ID, Description, Admin, Name) values (176, 'Abscess of eyelid', 1, 'libero nam dui');
insert into Groups (ID, Description, Admin, Name) values (177, 'Traumatic rupture of unspecified ligament of left index finger at metacarpophalangeal and interphalangeal joint, subsequent encounter', 0, 'quisque');
insert into Groups (ID, Description, Admin, Name) values (178, 'Monoplegia of upper limb following other nontraumatic intracranial hemorrhage', 0, 'sit amet');
insert into Groups (ID, Description, Admin, Name) values (179, 'Other disorders of bone development and growth, unspecified ankle and foot', 1, 'elementum');
insert into Groups (ID, Description, Admin, Name) values (180, 'Adverse effect of antimycobacterial drugs, subsequent encounter', 0, 'natoque penatibus');
insert into Groups (ID, Description, Admin, Name) values (181, 'Type II occipital condyle fracture, right side, initial encounter for open fracture', 1, 'lectus');
insert into Groups (ID, Description, Admin, Name) values (182, 'Toxic effect of contact with other venomous plant, accidental (unintentional), subsequent encounter', 1, 'metus');
insert into Groups (ID, Description, Admin, Name) values (183, 'Injury of ulnar nerve at upper arm level, unspecified arm, subsequent encounter', 1, 'in');
insert into Groups (ID, Description, Admin, Name) values (184, 'Poisoning by antiparkinsonism drugs and other central muscle-tone depressants, accidental (unintentional), subsequent encounter', 0, 'odio');
insert into Groups (ID, Description, Admin, Name) values (185, 'Laceration of flexor muscle, fascia and tendon of other finger at wrist and hand level, subsequent encounter', 0, 'faucibus');
insert into Groups (ID, Description, Admin, Name) values (186, 'Other secondary osteonecrosis, right femur', 1, 'lacus morbi quis');
insert into Groups (ID, Description, Admin, Name) values (187, 'Nondisplaced fracture of olecranon process with intraarticular extension of left ulna, subsequent encounter for closed fracture with nonunion', 0, 'pellentesque');
insert into Groups (ID, Description, Admin, Name) values (188, 'Encounter for other orthopedic aftercare', 1, 'quam');
insert into Groups (ID, Description, Admin, Name) values (189, 'Other disorders of bone', 0, 'curae mauris viverra');
insert into Groups (ID, Description, Admin, Name) values (190, 'Other chronic obstructive pulmonary disease', 1, 'vel dapibus at');
insert into Groups (ID, Description, Admin, Name) values (191, 'Spinal muscular atrophy, unspecified', 0, 'pulvinar nulla');
insert into Groups (ID, Description, Admin, Name) values (192, 'Burn of first degree of left elbow, sequela', 1, 'porta volutpat erat');
insert into Groups (ID, Description, Admin, Name) values (193, 'Other injury of extensor muscle, fascia and tendon of right index finger at forearm level, subsequent encounter', 1, 'sollicitudin vitae');
insert into Groups (ID, Description, Admin, Name) values (194, 'Enteroptosis', 0, 'vitae mattis');
insert into Groups (ID, Description, Admin, Name) values (195, 'Crepitant synovitis (acute) (chronic), left wrist', 0, 'et commodo');
insert into Groups (ID, Description, Admin, Name) values (196, 'Serous retinal detachment, unspecified eye', 1, 'nec molestie');
insert into Groups (ID, Description, Admin, Name) values (197, 'Sternal manubrial dissociation, subsequent encounter for fracture with routine healing', 0, 'enim lorem');
insert into Groups (ID, Description, Admin, Name) values (198, 'Superficial frostbite of unspecified foot, subsequent encounter', 1, 'eget');
insert into Groups (ID, Description, Admin, Name) values (199, 'Toxic effect of carbon monoxide from utility gas, undetermined, sequela', 0, 'convallis tortor');
insert into Groups (ID, Description, Admin, Name) values (200, 'Insect bite (nonvenomous) of right forearm', 0, 'libero rutrum');
